spring:
  application:
    name: eureka-server

server:
  port: 26001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:26001/eureka/
  server:
    renewalPercentThreshold: 0.49
    eviction-interval-timer-in-ms: 5000
